import type { Metadata } from "next";
import { UIProvider } from "./UIProvider";
import "./globals.css";
import { ThemeProvider } from "./context/ThemeContext";
import { GeolocationProvider } from "./context/GeeolocationContext";

export const metadata: Metadata = {
    title: "Weather App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <ThemeProvider>
                <GeolocationProvider>
                    <UIProvider>{children}</UIProvider>
                </GeolocationProvider>
            </ThemeProvider>
        </html>
    );
}
